docs_dir: docs
site_name: Python Deep Dive
repo_url: https://github.com/laurent-laporte-pro/python-deep-dive
edit_uri: edit/docs/docs/

theme:
  name: mkdocs # material
  logo: assets/python-deep-dive-logo.png
  favicon: assets/python-deep-dive-icon.ico
  prev_next_buttons_location: none
  features:
    - navigation.instant
    - navigation.top
    - navigation.expand
  #  - navigation.sections
  #   - header.autohide
  #   - toc.separate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - 'Index': 'index.md'


extra:
  generator: false
  version:
    provider: mike
plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://code.jquery.com/jquery-3.6.0.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

#markdown_extensions:
#  - attr_list
#  - toc:
#      permalink: true
#      toc_depth: 3
#  - pymdownx.emoji:
#      emoji_index: !!python/name:material.extensions.emoji.twemoji
#      emoji_generator: !!python/name:material.extensions.emoji.to_svg
#  - admonition
#  - pymdownx.details
#  - pymdownx.superfences
#  - pymdownx.tabbed

copyright: Copyright &copy; 2024 Laurent LAPORTE
